### ISSUE TITLE
Draw Assests

### ISSUE THREAD

**Issue by highskyeli** [highskyeli/project-mayham#1]
- [x] Tyler Durden (Main Character) @Madvil1in 
- [x] Tyler Durden (Alter Ego) @Madvil1in 
- [x] Demons @WilliamLievense 
- [x] Bartender @WilliamLievense 
- [x] Henchman @highskyeli 
- [x] Police @highskyeli

**Comment by highskyeli** [comment]
![Image](https://github.com/user-attachments/assets/d676a83d-46a3-4295-8288-0e02cd083042)
![Image](https://github.com/user-attachments/assets/1f567dde-57c4-41b8-8440-4ad6f863f386)
Here is the Henchman + Police

**Comment by WilliamLievense** [comment]
![Image](https://github.com/user-attachments/assets/f24892b6-4b7b-4c64-b0ae-9786d5d129cd)

**Comment by WilliamLievense** [comment]
![Image](https://github.com/user-attachments/assets/fba79493-52e5-46a8-86b2-2f5132e4f426)

**Comment by WilliamLievense** [comment]
![Image](https://github.com/user-attachments/assets/ffe753ba-c83f-475c-975c-8d71f438535b)

**Comment by WilliamLievense** [comment]
![Image](https://github.com/user-attachments/assets/4ea5890d-da20-4579-b0a1-7642acb36dfb)

**Comment by msorret** [comment]
@msorret

**Comment by Madvil1in** [comment]
![images](https://github.com/user-attachments/assets/a26acc5a-ac65-4b6c-a33c-3265681c7b0d)

**Comment by highskyeli** [comment]
![Image](https://github.com/user-attachments/assets/fee62774-ea65-47ca-b7a3-b02d8f5e6420)

**Comment by Madvil1in** [comment]
![images (1)](https://github.com/user-attachments/assets/e9a6d0e0-0579-4fc8-928d-c8746c936fac)

**Comment by Madvil1in** [comment]
![Image](https://github.com/user-attachments/assets/10c29109-e4e3-4fc7-819e-d5d6ebf3c646)
